# Generated by Django 3.2.12 on 2022-02-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('url', models.URLField()),
                ('price', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('condominium', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('iptu', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'Estimate Request',
                'verbose_name_plural': 'Estimate Requests',
                'db_table': 'estimate_request',
                'managed': True,
            },
        ),
    ]
