# Generated by Django 3.2.12 on 2022-02-07 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimaterequest',
            name='condominium',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimaterequest',
            name='iptu',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estimaterequest',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
