# Generated by Django 3.2.12 on 2022-02-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20220207_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimaterequest',
            name='phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
    ]
